server:
  port: 8081
dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.cctv.dubboprovider.service.impl
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: nacos://10.6.4.227:8848

spring:
  application:
    # Dubbo 应用名称
    name: dubbo-provider
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 10.6.4.227:8848
        register-enabled: true
