server:
  port: 8080
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://10.6.4.227:8848
  cloud:
    subscribed-services: dubbo-provider
spring:
  application:
    name: dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 10.6.4.227:8848
        register-enabled: true
  main:
    allow-bean-definition-overriding: true
